import { createFileRoute, useServerFn } from "@tanstack/react-start";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Loader2, Sparkles, Copy, Download, FileText } from "lucide-react";
import { toast } from "sonner";
import { generateLaudo } from "@/lib/laudos.functions";
import { useQueryClient } from "@tanstack/react-query";
